repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        additional_dependencies: [flake8]
        files: ^src/  # Да, имеенно с апострофом, чтобы прогонялся весь код в src

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false
